# Generated by Django 3.1 on 2021-01-22 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_product_stock'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
